# Generated by Django 5.2.3 on 2025-06-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='book',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Embed ссылка с YouTube', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.DateField(),
        ),
    ]
