# Generated by Django 5.2.3 on 2025-06-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_book_youtube_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='youtube_url',
            field=models.TextField(blank=True, help_text='Embed ссылка с YouTube', null=True),
        ),
    ]
